### ISSUE TITLE
Issues in the Appendix G in FAR/AIM

### ISSUE THREAD

**Issue by dyneilpat** [tekkinnovations/faraim-base-packages#3]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/32177798/169740522-944dcb86-59e8-40a1-99d7-400bf5e05559.png">

There is a customer complain about some issues with the Appendix G.

The problem is in the recent update, the Part 91 of 14 CFR was included there (which I think it was erroneously added).

This makes Appendix G very lengthy with irrelevant texts. (See video) and makes it difficult for the customer to access it.

https://www.dropbox.com/s/geigcw4voiawb04/Image%20from%20iOS.MP4?dl=0

@kaom, can we removed this Part 91 of 14 CFR from the appendix G?

**Comment by kasimte** [comment]
@dyneilpat FYI, you flagged a user that wasn't Kaom. Please use @kaomte.

The dropbox video above shows the Changes page and not the Appendix G page. Can you screenshot the issue with Appendix G and not the Changes pages?

**Comment by dyneilpat** [comment]
Hi @kasimte , @kaomte  the issue is on the highlighted changes page.  We need to get rid of it. 

Here's the screenshot of the Appendix G page.

https://www.dropbox.com/s/3099vxrzpfzdefl/Image%20from%20iOS%20%281%29.MP4?dl=0

**Comment by kaomte** [comment]
is that the latest aim data?

**Comment by kaomte** [comment]
I don't see any appendices in the AIM Data.
